export const TYPES_TO_SPANISH: any = {
    "normal": "Normal",
    "steel": "Acero",
    "ghost": "Fantasma",
    "electric": "Eléctrico",
    "poison": "Veneno",
    "bug": "Bicho",
    "psychic": "Psíquico",
    "fire": "Fuego",
    "flying": "Volador",
    "ice": "Hielo",
    "dark": "Siniestro",
    "dragon": "Dragón",
    "water": "Agua",
    "fairy": "Hada",
    "fighting": "Lucha",
    "rock": "Roca",
    "grass": "Planta",
    "ground": "Tierra",
}